### ISSUE TITLE
[BUG] Toolchain removed, needs to be changed to the updated ver.

### ISSUE THREAD

**Issue by classicrocker883** [shadow578/Marlin-H32#48]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

this toolchain has been removed, and replaced
https://github.com/platformio/platformio-core/issues/4741

after trying to compile, I receive this error:
```r
Processing HC32F460xCxx_AQUILA_V101 (platform: https://github.com/shadow578/platform-hc32f46x.git; board: generic_hc32f460; framework: arduino)
--------------------------------------------------------------------------------
Platform Manager: Installing git+https://github.com/shadow578/platform-hc32f46x.git
git version 2.[42](https://github.com/classicrocker883/MRiscoCProUI/actions/runs/6508150014/job/17676940915#step:8:43).0
Cloning into '/home/runner/.platformio/.cache/tmp/pkg-installing-21db8mih'...
Platform Manager: hc32f[46](https://github.com/classicrocker883/MRiscoCProUI/actions/runs/6508150014/job/17676940915#step:8:47)x@1.0.0+sha.33fc21f has been installed!
Tool Manager: Installing platformio/toolchain-gccarmnoneeabi @ =1.120201.221222
UnknownPackageError: Could not find the package with 'platformio/toolchain-gccarmnoneeabi @ =1.120201.221222' requirements for your system 'linux_x86_64'
Error: Process completed with exit code 1.
```
<br>

We have just removed the broken `1.120201.221222` version. Please try the recently published [1.120301.0](https://registry.platformio.org/tools/platformio/toolchain-gccarmnoneeabi)

_Originally posted by @ivankravets in https://github.com/platformio/platformio-core/issues/4741#issuecomment-1731514133_

I believe this is the file that needs to be changed:  
https://github.com/shadow578/platform-hc32f46x/blob/main/platform.json
### Bug Timeline

recently, probably started 3 weeks ago when toolchain was removed

### Version of Marlin Firmware

current

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

so this toolchain needs to be updated/changed in the framework repos

toolchain-gccarmnoneeabi @ =1.120201.221222 >> 1.120301.0 

https://registry.platformio.org/tools/platformio/toolchain-gccarmnoneeabi (12.3.1)

**Comment by shadow578** [comment]
thanks for the heads-up, should be fixed by https://github.com/shadow578/platform-hc32f46x/pull/4
